name = "NeuroAnalyzer"
uuid = "b40dcafa-b65c-47ad-a230-3174ba5cadd1"
authors = ["Adam Wysoki≈Ñski <adam.wysokinski@umed.lodz.pl>"]
version = "0.23.3"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ContinuousWavelets = "96eb917e-2868-4417-9cb6-27e7ff17528f"
CubicSplines = "9c784101-8907-5a6d-9be6-98f00873c89b"
DICOM = "a26e6606-dd52-5f6a-a97f-4f611373d757"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Deconvolution = "41ba435c-a500-5816-a783-a9707c6f5f3a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FIRLSFilterDesign = "1d969ca1-ee82-491a-b198-7f2f63a25c18"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FindPeaks1D = "d8961e24-b28b-4efb-8e50-1c680b9a7431"
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
InformationMeasures = "96684042-fbdc-5399-9b8e-d34e539a126c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Jacobi = "83f21c0b-4282-5fbc-9e3f-f6da3d2e584c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SavitzkyGolay = "c4bf5708-b6a6-4fbe-bcd0-6850ed671584"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
Simpson = "8e55fee6-e67b-4637-994c-810009a3f62d"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsKit = "2cb19f9e-ec4d-5c53-8573-a4542a68d3f0"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Wavelets = "29a6e085-ba6d-5f35-a997-948ac2efa89a"
WaveletsExt = "8f464e1e-25db-479f-b0a5-b7680379e03f"

[compat]
julia = "1.0"
